/* ============================================================
   NEXTGEN CHALLENGE — Sample Data
   ============================================================ */

const DB = {
  challenges: [
    { id: "c1", title: "Build an AI-Powered Website", category: "AI", sub: "AI & Web Development",
      difficulty: "Intermediate", participants: 248, reward: 500, deadline: 7, status: "open",
      icon: "🤖", blurb: "Create a website that uses an AI model to deliver real value.",
      overview: "Design and build a working website that integrates an AI model (LLM, image generation, or prediction) to solve a real user problem.",
      brief: "You'll ship a full-stack AI web app. Focus on a clear use case, a great UI, and responsible AI handling.",
      requirements: ["Live, deployed website", "A working AI integration", "Responsive design", "A short README"],
      rules: ["One entry per team", "Must be original work", "Open source the code"],
      criteria: [["Creativity", 25], ["Functionality", 30], ["Design", 20], ["Innovation", 25]],
      gradient: "linear-gradient(135deg,#7c3aed,#a855f7)" },
    { id: "c2", title: "No-Code Automation Sprint", category: "Automation", difficulty: "beginner",
      participants: 312, reward: 300, deadline: 4, status: "open", icon: "⚙️",
      blurb: "Build a no-code automation that saves at least 2 hours a week.", gradient: "linear-gradient(135deg,#0ea5e9,#7c3aed)" },
    { id: "c3", title: "Futuristic UI Design Battle", category: "Design", difficulty: "advanced",
      participants: 176, reward: 400, deadline: 5, status: "open", icon: "🎨",
      blurb: "Design a next-gen dashboard with stunning visual hierarchy and motion.", gradient: "linear-gradient(135deg,#ff4fd8,#7c3aed)" },
    { id: "c4", title: "Web3 Wallet Experience", category: "Web3", difficulty: "advanced",
      participants: 92, reward: 600, deadline: 12, status: "open", icon: "⛓️",
      blurb: "Redesign the on-ramp and wallet experience for a Web3 product.", gradient: "linear-gradient(135deg,#8b5cf6,#6366f1)" },
    { id: "c5", title: "30-Day Content Streak", category: "Content Creation", difficulty: "beginner",
      participants: 540, reward: 250, deadline: 3, status: "ending", icon: "✍️",
      blurb: "Publish daily for 30 days across a channel of your choice.", gradient: "linear-gradient(135deg,#22d3ee,#a855f7)" },
    { id: "c6", title: "Robotics Vision Hack", category: "AI", difficulty: "intermediate",
      participants: 198, reward: 450, deadline: 9, status: "open", icon: "🦾",
      blurb: "Build a computer-vision pipeline that makes a robot react to its environment.", gradient: "linear-gradient(135deg,#f43f5e,#8b5cf6)" },
    { id: "c7", title: "Smart Contract Challenge", category: "Web3", difficulty: "advanced",
      participants: 64, reward: 550, deadline: 6, status: "open", icon: "📜",
      blurb: "Deploy a secure, gas-efficient smart contract for a real use case.", gradient: "linear-gradient(135deg,#a855f7,#6366f1)" },
    { id: "c8", title: "Design a Landing Page", category: "Design", difficulty: "beginner",
      participants: 410, reward: 200, deadline: 0, status: "completed", icon: "🖥️",
      blurb: "Create a high-converting landing page for a fictional product.", gradient: "linear-gradient(135deg,#ff9d6b,#ff4fd8)" },
    { id: "c9", title: "AI Research Digest", category: "AI", difficulty: "intermediate",
      participants: 130, reward: 350, deadline: 0, status: "completed", icon: "📚",
      blurb: "Summarize the week's top AI papers into an accessible digest.", gradient: "linear-gradient(135deg,#7c3aed,#22d3ee)" },
  ],
  users: [
    { id: "u1", name: "Crypto bunny", handle: "cryptobunny", avatar: "cryptobunny.png", bio: "Full-stack dev & AI tinkerer. Building the future one PR at a time.",
      xp: 4820, points: 12900, wins: 3, completed: 12, rank: 1,
      badges: ["🏆 First Challenge","🔥 Challenge Streak","💡 Innovator","👑 Champion"],
      projects: ["p1","AI Research Digest","AI"], gradient: "linear-gradient(135deg,#8b5cf6,#ff4fd8)" },
    { id: "u2", name: "Micheal cryt", handle: "michealcryt", avatar: "michealcryt.png", bio: "Design engineer. Obsessed with motion and micro-interactions.",
      xp: 4100, points: 1100, wins: 2, completed: 9, rank: 2,
      badges: ["🎨 Futuristic UI","💡 Innovator","⚡ Speed Builder"],
      projects: ["p2","Futuristic UI Kit","Design"], gradient: "linear-gradient(135deg,#ff4fd8,#f59e0b)" },
    { id: "u3", name: "Dropper", handle: "dropper", avatar: "dropper.png", bio: "Automation enthusiast. If it's repetitive, I automate it.",
      xp: 3980, points: 980, wins: 3, completed: 10, rank: 3,
      badges: ["#🎯 Workflow Hero","🚀 Builder"],
      projects: ["p3","No-Code Workflows","Automation"], gradient: "linear-gradient(135deg,#22d3ee,#8b5cf6)" },
    { id: "u4", name: "Springwind", handle: "springwind", avatar: "springwind.png", bio: "Web3 native. Smart contracts are my love language.",
      xp: 3520, points: 870, wins: 1, completed: 7, rank: 4,
      badges: ["⛓️ DeFi Explorer","💎 Elite Creator"],
      projects: ["p4","Wallet UX","Web3"], gradient: "linear-gradient(135deg,#6366f1,#22d3ee)" },
    { id: "u5", name: "Aelvion", handle: "aelvion", avatar: "aelvion.png", bio: "Content creator, 100k+ views. Copy is code for humans.",
      xp: 3210, points: 760, wins: 4, completed: 8, rank: 5,
      badges: ["✍️ 30-Day Streak","🔥 Challenge","💎 Content King"],
      projects: ["p5","30-Day Content","Content"], gradient: "linear-gradient(135deg,#f43f5e,#8b5cf6)" },
    { id: "u6", name: "Gabbie", handle: "gabbie", avatar: "gabbie.png", bio: "Robotics grad student. Vision models are my side hustle.",
      xp: 2890, points: 690, wins: 2, completed: 6, rank: 6,
      badges: ["🦾 Robotics","🚀 Builder"],
      projects: ["p6","VisionBot","AI"], gradient: "linear-gradient(135deg,#10b981,#8b5cf6)" },
    { id: "u7", name: "Fela-mayor", handle: "felamayor", avatar: "felamayor.png", bio: "Backend & smart contracts.",
      xp: 2640, points: 620, wins: 1, completed: 5, rank: 7,
      badges: ["📜 Smart Contracts"], gradient: "linear-gradient(135deg,#a855f7,#ec4899)" },
    { id: "u8", name: "Aisha B.", handle: "aisha", bio: "Frontend + accessibility advocate.",
      xp: 2450, points: 540, wins: 1, completed: 5, rank: 8,
      badges: ["💡 Innovator"], gradient: "linear-gradient(135deg,#8b5cf6,#22d3ee)" },
    { id: "u9", name: "Owen P.", handle: "owen", bio: "Automation & APIs.",
      xp: 2210, points: 470, wins: 0, completed: 4, rank: 9,
      badges: ["⚙️ Automator"], gradient: "linear-gradient(135deg,#ec4899,#f59e0b)" },
    { id: "u10", name: "Nia S.", handle: "nia", bio: "Creative technologist.",
      xp: 1980, points: 400, wins: 1, completed: 3, rank: 10,
      badges: ["🚀 Builder"], gradient: "linear-gradient(135deg,#f59e0b,#8b5cf6)" },
  ],
  projects: [
    { id: "p1", name: "MindForge", creator: "Crypto bunny", handle: "cryptobunny", category: "AI",
      desc: "An AI-powered study companion that turns notes into interactive quizzes.",
      likes: 342, views: 2100, featured: true, winner: true, emoji: "🧠",
      gradient: "linear-gradient(135deg,#7c3aed,#a855f7)" },
    { id: "p2", name: "OrbitUI", creator: "Micheal cryt", handle: "michealcryt", category: "Design",
      desc: "A futuristic component library with glowing motion primitives.", likes: 298, views: 1750, featured: true, emoji: "🪐",
      gradient: "linear-gradient(135deg,#ff4fd8,#7c3aed)" },
    { id: "p3", name: "ZapDesk", creator: "Dropper", handle: "dropper", category: "Automation",
      desc: "Automated support ticketing pipeline that saves 12h/week.",
      likes: 210, views: 1380, featured: true, emoji: "⚙️",
      gradient: "linear-gradient(135deg,#22d3ee,#8b5cf6)" },
    { id: "p4", name: "Wallet3", creator: "Springwind", handle: "springwind", category: "Web3",
      desc: "A frictionless multi-chain wallet onboarding flow.",
      likes: 180, views: 940, featured: false, winner: true, emoji: "⛓️",
      gradient: "linear-gradient(135deg,#6366f1,#22d3ee)" },
    { id: "p5", name: "30Days.io", creator: "Aelvion", handle: "aelvion", category: "Content",
      desc: "A 30-day content streak tracker with community accountability.",
      likes: 164, views: 820, featured: false, emoji: "✍️",
      gradient: "linear-gradient(135deg,#f43f5e,#8b5cf6)" },
    { id: "p6", name: "VisionBot", creator: "Gabbie", handle: "gabbie", category: "AI",
      desc: "Open-source computer-vision bot that avoids and maps obstacles.",
      likes: 148, views: 610, featured: false, emoji: "🦾",
      gradient: "linear-gradient(135deg,#10b981,#8b5cf6)" },
  ],
  badges: [
    { name: "First Challenge", icon: "🏆", desc: "Complete your first challenge", cats: "starter" },
    { name: "Challenge Streak", icon: "🔥", desc: "Complete 3 challenges in a row", cats: "streak" },
    { name: "Innovator", icon: "💡", desc: "Submit an original, creative project", cats: "creator" },
    { name: "Builder", icon: "🚀", desc: "Submit your first project", cats: "starter" },
    { name: "Champion", icon: "👑", desc: "Win any challenge", cats: "win" },
    { name: "Speed Builder", icon: "⚡", desc: "Submit within 24h of joining", cats: "speed" },
    { name: "Top 10", icon: "🎯", desc: "Reach the global Top 10", cats: "rank" },
    { name: "Elite Creator", icon: "💎", desc: "Reach 5,000 XP and 10 wins", cats: "elite" },
  ],
  activity: [
    { type: "join", text: "Joined the AI-Powered Website challenge", time: "2h ago", icon: "🎯" },
    { type: "xp", text: "Earned 100 XP for completion", time: "5h ago", icon: "⭐" },
    { type: "badge", text: "Unlocked the 'Builder' badge", time: "1d ago", icon: "🚀" },
    { type: "submit", text: "Submitted project to No-Code Automation Sprint", time: "2d ago", icon: "📦" },
  ],
  levels: [
    { n: 1, name: "Explorer", min: 0 },
    { n: 2, name: "Creator", min: 1000 },
    { n: 3, name: "Builder", min: 2500 },
    { n: 4, name: "Innovator", min: 4500 },
    { n: 5, name: "NextGen Elite", min: 7000 },
  ]
};

// default joined challenges for the demo user
DB.defaultJoined = ["c1", "c5"];

function nextId(prefix){ return prefix + "_" + Date.now().toString(36) + Math.random().toString(36).slice(2,6); }